trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: 'build-image'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: Docker@2
    displayName: Build miniforge3 image
    inputs:
      command: build
      Dockerfile: miniforge3/Dockerfile
